spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    password: changeme
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect