logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: trace
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
      show-sql: true
